#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# default file copies first run
if [ ! -d /config/.config/openbox/autostart ]; then
    mkdir -p /config/.config/openbox
    cp /defaults/autostart /config/.config/openbox/autostart
    lsiown -R abc:abc /config/.config/openbox
fi
