#!/usr/bin/with-contenv bash

# default file copies first run
[[ ! -d /config/.config/openbox/autostart ]] && \
	mkdir -p /config/.config/openbox && \
        cp /defaults/autostart /config/.config/openbox/autostart && \
	chown -R abc:abc /config/.config/openbox
